openapi: 3.0.2
info:
  title: MoldON API V1
  version: 1.0.0
  description: |- 
    3D도면 이미지화
    - 3D도면을 업로드하여 7개의 각도에서 보여지는 형상을 이미지로 다운로드 할 수 있는 기능입니다. 
  x-logo: 
    url: 'https://moldmecca.github.io/Convert3DtoImages/MoldON_logo.png'
    altText: A Logo image of MoldON
paths:
  /Convert3DtoImages:
    post:
      summary: Convert3DtoImages
      tags:
        - 3D도면 이미지화
      description: >-
        3D 도면 이미지화
      parameters: []
      security:
        - APIKeyAuth: []
      responses:
        '200':
          description: successfully authenticated
          content:
            application/json:
              schema:
                type: file
                items:
                  $ref: '#/components/schemas/Response_Boundbox'
        '201':
          description: igs or stp 파일이 아닌 경우
          content:
            application/json:
              example:
                detail : "Error : Only igs or stp files are supported." 
        '403':
          description: API KEY 오류
          content:
            application/json:
              example:
                detail: "The API-key is invalid.. or The API-key has expired.." 
        '501':
          description: 이미지 변환 오류
          content:
            application/json:
              example:
                detail : " Error : error message"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody_Bbox'
servers:
  - url: https://api.moldon.org/v1
    description: Production server
security:
  - APIKeyAuth: []
components:
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      name: x-mold-apigw-api-key
      in: header
  schemas:
    Response_Boundbox:
      description: zip files of converted 7 images
      type: file
      properties:
        zip파일:
          description: 원본 파일명과 동일한 명의 zip파일
    RequestBody_Bbox:
      description: Request file-name and file
      required: ["file_3d"]
      type: object
      properties:
        file_3d:
          type: file
          format: binary
          description: 실제 도면 파일(**stp, igs 파일만 가능**)